Repository TBMCPlugins/PluginConfigs, pull requests merged in 2018-06, with the labels that each got.

#3 Increase town blocks per player to 48, unlimited extra plots with 1.5 price multiplier
  Towny/settings/config.yml
Labels: Config Change

#9 Changes made to grant perms for PlotSquared
  PermissionsEx/permissions.yml
Labels: Config Change, enhancement

#8 Turning off Protection Enchantment Limiter
  EnchantLimit/config.yml
Labels: Config Change, enhancement

#10 Add experimental JVM args for potential performance improvements
  ServerRunner/config.yml
Labels: Config Change, enhancement

#19 Changed to commenting instead of deleting
  Jobs/jobConfig.yml
Labels: bug

#20 Narrowing visibility of Luna World
  dynmap/worlds.txt
Labels: Config Change, good first issue

#18 Remove slime exploit
  Jobs/jobConfig.yml
Labels: bug
